// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:app_core/shared/utils/logger.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUwyEsiBdxDb94bdl7JsoGs4_kneLZGSs',
    appId: '1:563887997529:android:6502e7d1f5d76ce36fa748',
    messagingSenderId: '563887997529',
    projectId: 'gis-dak-lak',
    storageBucket: 'gis-dak-lak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWmLUcV_UuqE1E4vvR4v0M3p1-L4wX9lE',
    appId: '1:563887997529:ios:1dc49fe7a700c83d6fa748',
    messagingSenderId: '563887997529',
    projectId: 'gis-dak-lak',
    storageBucket: 'gis-dak-lak.firebasestorage.app',
  );
}

Future<void> logFcmToken() async {
  await Firebase.initializeApp(); // nếu bạn đang init bằng DefaultFirebaseOptions thì chỉ OK trên Android trong file hiện tại
  await FirebaseMessaging.instance
      .requestPermission(); // cần thiết cho iOS, và hữu ích để đảm bảo quyền thông báo

  final token = await FirebaseMessaging.instance.getToken();
  AppLogger.debug('FCM token: $token');

  FirebaseMessaging.instance.onTokenRefresh.listen((t) {
    AppLogger.debug('FCM token refreshed: $t');
  });
}
